/*
 * GT6 Port: 1.7.10 Forge → 1.21.1 NeoForge
 * Source: gregtech/loaders/b/Loader_Worldgen.java
 * Purpose: Enumerate GT6 ore and stone materials used by stone-layer worldgen.
 * Status: PORTED
 * Notes: IDs are sequential and used for block state encoding.
 */
package com.gt6ceu.gregtech.worldgen;

import java.util.Arrays;

public enum GtOreMaterial {
    EMPTY(0, "empty"),
    STONE(1, "stone"),
    DEEPSLATE(2, "deepslate"),
    KOMATIITE(3, "komatiite"),
    GABBRO(4, "gabbro"),
    BASALT(5, "basalt"),
    ANDESITE(6, "andesite"),
    MARBLE(7, "marble"),
    LIMESTONE(8, "limestone"),
    GRANITE_BLACK(9, "granite_black"),
    GRANITE_RED(10, "granite_red"),
    GRANITE(11, "granite"),
    DIORITE(12, "diorite"),
    SCHIST_GREEN(13, "schist_green"),
    SCHIST_BLUE(14, "schist_blue"),
    SHALE(15, "shale"),
    SLATE(16, "slate"),
    QUARTZITE(17, "quartzite"),
    KIMBERLITE(18, "kimberlite"),
    OILSHALE(19, "oilshale"),
    DOLOMITE(20, "dolomite"),
    CHALK(21, "chalk"),
    TALC(22, "talc"),
    SAND(23, "sand"),
    RED_SAND(24, "red_sand"),
    SILTSTONE(25, "siltstone"),
    KCL(26, "kcl"),
    KIO3(27, "kio3"),
    KNO3(28, "kno3"),
    NA_CL(29, "nacl"),
    NITER(30, "niter"),
    LIGNITE(31, "lignite"),
    COAL(32, "coal"),
    GRAPHITE(33, "graphite"),
    S(34, "sulfur"),
    ALMANDINE(35, "almandine"),
    ALEXANDRITE(36, "alexandrite"),
    AMBER(37, "amber"),
    AMBER_DOMINICAN(38, "amber_dominican"),
    AMETHYST(39, "amethyst"),
    ANDRADITE(40, "andradite"),
    APATITE(41, "apatite"),
    AQUAMARINE(42, "aquamarine"),
    ARSENOPYRITE(43, "arsenopyrite"),
    ASBESTOS(44, "asbestos"),
    AU(45, "gold"),
    AZURITE(46, "azurite"),
    BALAS_RUBY(47, "balas_ruby"),
    BARITE(48, "barite"),
    BASTNASITE(49, "bastnasite"),
    BAUXITE(50, "bauxite"),
    BIXBITE(51, "bixbite"),
    BLUE_SAPPHIRE(52, "blue_sapphire"),
    BLUE_TOPAZ(53, "blue_topaz"),
    BONE(54, "bone"),
    BORAX(55, "borax"),
    BROMARGYRITE(56, "bromargyrite"),
    BROWN_LIMONITE(57, "brown_limonite"),
    CASSITERITE(58, "cassiterite"),
    CERTUS_QUARTZ(59, "certus_quartz"),
    CH4(60, "methane"),
    CHALCOPYRITE(61, "chalcopyrite"),
    CHROMITE(62, "chromite"),
    CINNABAR(63, "cinnabar"),
    COBALTITE(64, "cobaltite"),
    COLTAN(65, "coltan"),
    COLUMBITE(66, "columbite"),
    COOPERITE(67, "cooperite"),
    CRAPONITE(68, "craponite"),
    CU(69, "copper"),
    DIAMOND(70, "diamond"),
    DIATOMITE(71, "diatomite"),
    DIOPTASE(72, "dioptase"),
    EMERALD(73, "emerald"),
    FERBERITE(74, "ferberite"),
    FE2O3(75, "hematite"),
    FLUORITE_WHITE(76, "fluorite_white"),
    GALENA(77, "galena"),
    GARNIERITE(78, "garnierite"),
    GOSHENITE(79, "goshenite"),
    GROSSULAR(80, "grossular"),
    GREEN_SAPPHIRE(81, "green_sapphire"),
    HELIODOR(82, "heliodor"),
    HUEBNERITE(83, "huebnerite"),
    ILMENITE(84, "ilmenite"),
    IR(85, "iridium"),
    KESTERITE(86, "kesterite"),
    KYANITE(87, "kyanite"),
    LEPIDOLITE(88, "lepidolite"),
    MGCO3(89, "mgco3"),
    MALACHITE(90, "malachite"),
    MAXIXE(91, "maxixe"),
    MITHRIL(92, "mithril"),
    MN_O2(93, "mno2"),
    MONAZITE(94, "monazite"),
    MORGANITE(95, "morganite"),
    MOLYBDENITE(96, "molybdenite"),
    OPAL(97, "opal"),
    ORANGE_SAPPHIRE(98, "orange_sapphire"),
    PB(99, "lead"),
    PERIDOT(100, "peridot"),
    PENTLANDITE(101, "pentlandite"),
    PERLITE(102, "perlite"),
    PHOSPHORITE(103, "phosphorite"),
    PHOSPHORUS_RED(104, "phosphorus_red"),
    PITCHBLENDE(105, "pitchblende"),
    PO4(106, "po4"),
    POWELLITE(107, "powellite"),
    PYRITE(108, "pyrite"),
    PYROPE(109, "pyrope"),
    PURPLE_SAPPHIRE(110, "purple_sapphire"),
    REDSTONE(111, "redstone"),
    RUBY(112, "ruby"),
    SAPPHIRE(113, "sapphire"),
    SCHEELITE(114, "scheelite"),
    SPESSARTINE(115, "spessartine"),
    SPHALERITE(116, "sphalerite"),
    SPINEL(117, "spinel"),
    SPODUMENE(118, "spodumene"),
    SPERRYLITE(119, "sperrylite"),
    STANNITE(120, "stannite"),
    STIBNITE(121, "stibnite"),
    TANZANITE(122, "tanzanite"),
    TANTALITE(123, "tantalite"),
    TETRAHEDRITE(124, "tetrahedrite"),
    TH(125, "thorium"),
    TIO2(126, "tio2"),
    TOPAZ(127, "topaz"),
    TUNGSTATE(128, "tungstate"),
    URANINITE(129, "uraninite"),
    UVAROVITE(130, "uvarovite"),
    WOLFRAMITE(131, "wolframite"),
    WULFENITE(132, "wulfenite"),
    YELLOW_LIMONITE(133, "yellow_limonite"),
    YELLOW_SAPPHIRE(134, "yellow_sapphire"),
    ADAMANTINE(135, "adamantine"),
    AG(136, "silver"),
    AL2O3(137, "al2o3"),
    AMBROSIUM(138, "ambrosium"),
    ANCIENT_DEBRIS(139, "ancient_debris"),
    BI(140, "bismuth"),
    BISCHOFITE(141, "bischofite"),
    BLACK_QUARTZ(142, "black_quartz"),
    CHEESE(143, "cheese"),
    CHIMERITE(144, "chimerite"),
    DATOLITE(145, "datolite"),
    DESH(146, "desh"),
    DOLAMIDE(147, "dolamide"),
    DURANIUM_HEXAASTATIDE(148, "duranium_hexaastatide"),
    DURANIUM_HEXABROMIDE(149, "duranium_hexabromide"),
    DURANIUM_HEXACHLORIDE(150, "duranium_hexachloride"),
    DURANIUM_HEXAFLUORIDE(151, "duranium_hexafluoride"),
    DURANIUM_HEXAIODIDE(152, "duranium_hexaiodide"),
    EFRINE(153, "efrine"),
    ENDIUM(154, "endium"),
    EUDIALYTE(155, "eudialyte"),
    GLAUCONITE(156, "glauconite"),
    GYPSUM(157, "gypsum"),
    HEXORIUM_BLACK(158, "hexorium_black"),
    HEXORIUM_BLUE(159, "hexorium_blue"),
    HEXORIUM_GREEN(160, "hexorium_green"),
    HEXORIUM_RED(161, "hexorium_red"),
    HEXORIUM_WHITE(162, "hexorium_white"),
    INFUSED_AIR(163, "infused_air"),
    INFUSED_EARTH(164, "infused_earth"),
    INFUSED_ENTROPY(165, "infused_entropy"),
    INFUSED_FIRE(166, "infused_fire"),
    INFUSED_ORDER(167, "infused_order"),
    INFUSED_WATER(168, "infused_water"),
    LAPIS(169, "lapis"),
    LAZURITE(170, "lazurite"),
    MICA(171, "mica"),
    MILKY_QUARTZ(172, "milky_quartz"),
    MO(173, "molybdenum"),
    ND(174, "neodymium"),
    NI(175, "nickel"),
    NIKOLITE(176, "nikolite"),
    NAQUADAH(177, "naquadah"),
    OCTINE(178, "octine"),
    PD(179, "palladium"),
    PHOSPHORUS_BLUE(180, "phosphorus_blue"),
    PINALITE(181, "pinalite"),
    POLLUCITE(182, "pollucite"),
    POTASSIUM_FELDSPAR(183, "potassium_feldspar"),
    PT(184, "platinum"),
    RUSSELLITE(185, "russellite"),
    SE(186, "selenium"),
    SMITHSONITE(187, "smithsonite"),
    SN(188, "tin"),
    SODALITE(189, "sodalite"),
    SUGILITE(190, "sugilite"),
    SYRMORITE(191, "syrmorite"),
    TRITANIUM_HEXAFLUORIDE(192, "tritanium_hexafluoride"),
    TRONA(193, "trona"),
    TRINIUM(194, "trinium"),
    VINTEUM(195, "vinteum"),
    ZANITE(196, "zanite"),
    ZEOLITE(197, "zeolite"),
    ZIRCON(198, "zircon"),
    ZN(199, "zinc");

    private final int id;
    private final String registryName;

    GtOreMaterial(int id, String registryName) {
        this.id = id;
        this.registryName = registryName;
    }

    public int getId() {
        return id;
    }

    public String getRegistryName() {
        return registryName;
    }

    public static int maxId() {
        return Arrays.stream(values()).mapToInt(GtOreMaterial::getId).max().orElse(0);
    }

    public static GtOreMaterial byId(int id) {
        for (GtOreMaterial material : values()) {
            if (material.id == id) {
                return material;
            }
        }
        return EMPTY;
    }
}
